### ISSUE TITLE
返回手势回合tabview的滑动删除冲突~

### ISSUE THREAD

**Issue by sd1435728** [Coneboy-k/KKNavigationController#6]
使用中出现和tabview滑动删除冲突的情况

**Comment by Coneboy-k** [comment]
这个需要自己在使用的view进行下手势判断了。你使用的是系统tableView 滑动吗？

**Comment by sd1435728** [comment]
是得，UITableView使用自带的向左滑动删除功能，但是那个手势被导航拦截了？这个有啥办法解决吗

**Comment by Coneboy-k** [comment]
这个需要在tableview所在的那个页面中，设置一下 手势的 传递。

在这个方法进行调节。
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
    return YES;
}

gestureRecognizer对象里面有 响应的view。 你看下UIGestureRecognizer的定义。

**Comment by sd1435728** [comment]
我去看看，谢谢

**Comment by Coneboy-k** [comment]
不知道 解决没有， 可以看看这个帖子https://www.v2ex.com/t/164804#reply3

**Comment by sd1435728** [comment]
谢谢已经解决了，是用和你发的链接一样的方法

**Comment by Coneboy-k** [comment]
解决就好~

**Comment by JxbSir** [comment]
如果使用了这个return NO，当前界面虽然支持了删除滑动，但是同时也失去了KKNav的功能，不觉得不应该妥协吗？
